workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: bonalumekey
    environment:
      vars:
        BUNDLE_ID: "com.bonalume.popoff"
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bonalume.popoff
        profile_name: prod_profile
        certificate_name: apple_dist_cert
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release -t lib/main.dart
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
